import { HalftoneData, GCodeOptions, GCodeOutput, HalftoneDot } from '@/types';

export type MachineType = 'grbl' | 'reprap' | 'marlin' | 'linuxcnc' | 'mach3';
export type OperationType = 'drilling' | 'engraving';

export interface GCodeGeneratorOptions extends GCodeOptions {
  machineType: MachineType;
  operationType: OperationType;
  toolDiameter?: number;
  depthPerPass?: number;
  maxDepth?: number;
  retractHeight?: number;
}

export interface GenerationStats {
  totalMoves: number;
  totalDistance: number;
  estimatedTime: number;
  minX: number;
  maxX: number;
  minY: number;
  maxY: number;
  minZ: number;
  maxZ: number;
}

export class GCodeGeneratorError extends Error {
  constructor(message: string, public readonly code: string) {
    super(message);
    this.name = 'GCodeGeneratorError';
  }
}

export class GCodeGenerator {
  private static readonly MACHINE_CONFIGS: Record<MachineType, {
    coordinateSystem: string;
    unitCommand: (units: 'mm' | 'inches') => string;
    spindleCommands: {
      start: (speed: number) => string;
      stop: string;
    };
    homeCommand: string;
    endProgram: string;
  }> = {
    grbl: {
      coordinateSystem: 'G54',
      unitCommand: (units) => units === 'mm' ? 'G21' : 'G20',
      spindleCommands: {
        start: (speed) => `M3 S${speed}`,
        stop: 'M5'
      },
      homeCommand: 'G28',
      endProgram: 'M30'
    },
    reprap: {
      coordinateSystem: 'G54',
      unitCommand: (units) => units === 'mm' ? 'G21' : 'G20',
      spindleCommands: {
        start: (speed) => `M3 S${speed}`,
        stop: 'M5'
      },
      homeCommand: 'G28',
      endProgram: 'M2'
    },
    marlin: {
      coordinateSystem: 'G54',
      unitCommand: (units) => units === 'mm' ? 'G21' : 'G20',
      spindleCommands: {
        start: (speed) => `M3 S${speed}`,
        stop: 'M5'
      },
      homeCommand: 'G28',
      endProgram: 'M2'
    },
    linuxcnc: {
      coordinateSystem: 'G54',
      unitCommand: (units) => units === 'mm' ? 'G21' : 'G20',
      spindleCommands: {
        start: (speed) => `M3 S${speed}`,
        stop: 'M5'
      },
      homeCommand: 'G53 G0 Z0',
      endProgram: 'M2'
    },
    mach3: {
      coordinateSystem: 'G54',
      unitCommand: (units) => units === 'mm' ? 'G21' : 'G20',
      spindleCommands: {
        start: (speed) => `M3 S${speed}`,
        stop: 'M5'
      },
      homeCommand: 'G28',
      endProgram: 'M30'
    }
  };

  private static validateInputs(halftoneData: HalftoneData, options: GCodeGeneratorOptions): void {
    if (!halftoneData || !halftoneData.dots || halftoneData.dots.length === 0) {
      throw new GCodeGeneratorError('No halftone data provided or no dots found', 'NO_DATA');
    }

    if (options.safeHeight <= options.workHeight) {
      throw new GCodeGeneratorError('Safe height must be greater than work height', 'INVALID_HEIGHTS');
    }

    if (options.feedRate <= 0 || options.plungeRate <= 0) {
      throw new GCodeGeneratorError('Feed rates must be positive', 'INVALID_FEED_RATES');
    }

    if (options.spindleSpeed < 0) {
      throw new GCodeGeneratorError('Spindle speed cannot be negative', 'INVALID_SPINDLE_SPEED');
    }
  }

  private static transformCoordinates(
    dots: HalftoneDot[],
    imageWidth: number,
    imageHeight: number,
    outputWidth: number,
    outputHeight: number,
    flipY: boolean = true
  ): HalftoneDot[] {
    const scaleX = outputWidth / imageWidth;
    const scaleY = outputHeight / imageHeight;

    return dots.map(dot => ({
      ...dot,
      x: dot.x * scaleX,
      y: flipY ? outputHeight - (dot.y * scaleY) : dot.y * scaleY
    }));
  }

  private static optimizeToolpath(dots: HalftoneDot[]): HalftoneDot[] {
    if (dots.length <= 1) return dots;

    // Simple nearest neighbor optimization
    const optimized: HalftoneDot[] = [];
    const remaining = [...dots];
    
    // Start with first dot
    optimized.push(remaining.shift()!);

    while (remaining.length > 0) {
      const current = optimized[optimized.length - 1];
      let nearestIndex = 0;
      let nearestDistance = Infinity;

      // Find nearest remaining dot
      remaining.forEach((dot, index) => {
        const distance = Math.sqrt(
          Math.pow(dot.x - current.x, 2) + Math.pow(dot.y - current.y, 2)
        );
        if (distance < nearestDistance) {
          nearestDistance = distance;
          nearestIndex = index;
        }
      });

      optimized.push(remaining.splice(nearestIndex, 1)[0]);
    }

    return optimized;
  }

  private static generateHeader(options: GCodeGeneratorOptions): string[] {
    const config = this.MACHINE_CONFIGS[options.machineType];
    const lines: string[] = [];
    
    // File header
    lines.push('; Generated by Halftone to G-code Converter');
    lines.push('; ' + new Date().toISOString());
    lines.push('; Machine Type: ' + options.machineType.toUpperCase());
    lines.push('; Operation: ' + options.operationType);
    lines.push(';');
    
    // Safety and initialization
    lines.push('G90'); // Absolute positioning
    lines.push(config.unitCommand(options.units)); // Units
    lines.push(config.coordinateSystem); // Coordinate system
    lines.push('G17'); // XY plane selection
    lines.push('G94'); // Feed rate mode (units per minute)
    
    // Reset position
    if (options.homeAfterJob) {
      lines.push(config.homeCommand);
    }
    
    // Move to safe height
    lines.push(`G0 Z${options.safeHeight.toFixed(3)}`);
    
    // Spindle setup
    if (options.spindleSpeed > 0) {
      lines.push(config.spindleCommands.start(options.spindleSpeed));
      lines.push('G4 P2'); // Dwell 2 seconds for spindle startup
    }
    
    // Coolant
    if (options.coolant) {
      lines.push('M8'); // Coolant on
    }
    
    lines.push(';');
    lines.push('; Begin toolpath');
    lines.push(';');
    
    return lines;
  }

  private static generateFooter(options: GCodeGeneratorOptions): string[] {
    const config = this.MACHINE_CONFIGS[options.machineType];
    const lines: string[] = [];
    
    lines.push(';');
    lines.push('; End toolpath');
    lines.push(';');
    
    // Return to safe height
    lines.push(`G0 Z${options.safeHeight.toFixed(3)}`);
    
    // Turn off spindle and coolant
    lines.push(config.spindleCommands.stop);
    if (options.coolant) {
      lines.push('M9'); // Coolant off
    }
    
    // Home if requested
    if (options.homeAfterJob) {
      lines.push(config.homeCommand);
    }
    
    // End program
    lines.push(config.endProgram);
    
    return lines;
  }

  static generateDrillingGCode(
    halftoneData: HalftoneData,
    options: GCodeGeneratorOptions,
    outputDimensions: { width: number; height: number }
  ): GCodeOutput {
    try {
      this.validateInputs(halftoneData, options);

      // Transform and optimize coordinates
      const transformedDots = this.transformCoordinates(
        halftoneData.dots,
        halftoneData.width,
        halftoneData.height,
        outputDimensions.width,
        outputDimensions.height
      );

      const optimizedDots = this.optimizeToolpath(transformedDots);
      
      const lines: string[] = [];
      let totalDistance = 0;
      let totalMoves = 0;
      let lastX = 0, lastY = 0;
      
      // Generate header
      lines.push(...this.generateHeader(options));
      
      // Generate drilling operations
      for (const dot of optimizedDots) {
        const x = dot.x.toFixed(3);
        const y = dot.y.toFixed(3);
        
        // Calculate depth based on intensity
        const depth = options.workHeight - (options.maxDepth || 1) * dot.intensity;
        
        // Rapid move to position
        lines.push(`G0 X${x} Y${y}`);
        
        // Drill operation
        lines.push(`G1 Z${depth.toFixed(3)} F${options.plungeRate}`);
        lines.push(`G0 Z${(options.retractHeight || options.safeHeight).toFixed(3)}`);
        
        // Calculate travel distance
        const distance = Math.sqrt(Math.pow(dot.x - lastX, 2) + Math.pow(dot.y - lastY, 2));
        totalDistance += distance;
        totalMoves++;
        
        lastX = dot.x;
        lastY = dot.y;
      }
      
      // Generate footer
      lines.push(...this.generateFooter(options));
      
      // Calculate bounds
      const bounds = this.calculateBounds(optimizedDots);
      
      // Estimate time (rough calculation)
      const rapidTime = totalDistance / (options.feedRate * 2); // Assume rapid is 2x feed rate
      const plungeTime = (optimizedDots.length * (options.maxDepth || 1)) / options.plungeRate;
      const estimatedTime = rapidTime + plungeTime + 2; // Add 2 minutes for setup
      
      return {
        gcode: lines.join('\n'),
        estimatedTime,
        totalDistance,
        bounds: {
          minX: bounds.minX,
          maxX: bounds.maxX,
          minY: bounds.minY,
          maxY: bounds.maxY
        }
      };
    } catch (error) {
      throw error instanceof GCodeGeneratorError ? error :
        new GCodeGeneratorError(`Drilling G-code generation failed: ${error}`, 'DRILLING_ERROR');
    }
  }

  static generateEngravingGCode(
    halftoneData: HalftoneData,
    options: GCodeGeneratorOptions,
    outputDimensions: { width: number; height: number }
  ): GCodeOutput {
    try {
      this.validateInputs(halftoneData, options);

      // Transform and optimize coordinates
      const transformedDots = this.transformCoordinates(
        halftoneData.dots,
        halftoneData.width,
        halftoneData.height,
        outputDimensions.width,
        outputDimensions.height
      );

      const optimizedDots = this.optimizeToolpath(transformedDots);
      
      const lines: string[] = [];
      let totalDistance = 0;
      let totalMoves = 0;
      let lastX = 0, lastY = 0;
      
      // Generate header
      lines.push(...this.generateHeader(options));
      
      // Move to start position
      if (optimizedDots.length > 0) {
        const firstDot = optimizedDots[0];
        lines.push(`G0 X${firstDot.x.toFixed(3)} Y${firstDot.y.toFixed(3)}`);
        lines.push(`G1 Z${options.workHeight.toFixed(3)} F${options.plungeRate}`);
      }
      
      // Generate engraving moves with variable feed rates
      for (let i = 0; i < optimizedDots.length; i++) {
        const dot = optimizedDots[i];
        const x = dot.x.toFixed(3);
        const y = dot.y.toFixed(3);
        
        // Variable feed rate based on intensity
        const feedRate = Math.round(options.feedRate * (0.3 + 0.7 * dot.intensity));
        
        if (i === 0) {
          // First move, already positioned
          lines.push(`G1 X${x} Y${y} F${feedRate}`);
        } else {
          // Check if we need to lift for large moves
          const distance = Math.sqrt(
            Math.pow(dot.x - lastX, 2) + Math.pow(dot.y - lastY, 2)
          );
          
          if (distance > (options.toolDiameter || 1) * 3) {
            // Lift, rapid move, plunge
            lines.push(`G0 Z${(options.retractHeight || options.safeHeight).toFixed(3)}`);
            lines.push(`G0 X${x} Y${y}`);
            lines.push(`G1 Z${options.workHeight.toFixed(3)} F${options.plungeRate}`);
          } else {
            // Direct engraving move
            lines.push(`G1 X${x} Y${y} F${feedRate}`);
          }
        }
        
        totalDistance += i > 0 ? Math.sqrt(Math.pow(dot.x - lastX, 2) + Math.pow(dot.y - lastY, 2)) : 0;
        totalMoves++;
        
        lastX = dot.x;
        lastY = dot.y;
      }
      
      // Generate footer
      lines.push(...this.generateFooter(options));
      
      // Calculate bounds
      const bounds = this.calculateBounds(optimizedDots);
      
      // Estimate time
      const avgFeedRate = options.feedRate * 0.65; // Average of variable feed rates
      const estimatedTime = (totalDistance / avgFeedRate) * 60 + 3; // Convert to minutes, add setup time
      
      return {
        gcode: lines.join('\n'),
        estimatedTime,
        totalDistance,
        bounds: {
          minX: bounds.minX,
          maxX: bounds.maxX,
          minY: bounds.minY,
          maxY: bounds.maxY
        }
      };
    } catch (error) {
      throw error instanceof GCodeGeneratorError ? error :
        new GCodeGeneratorError(`Engraving G-code generation failed: ${error}`, 'ENGRAVING_ERROR');
    }
  }

  static generate(
    halftoneData: HalftoneData,
    options: GCodeGeneratorOptions,
    outputDimensions: { width: number; height: number }
  ): GCodeOutput {
    try {
      switch (options.operationType) {
        case 'drilling':
          return this.generateDrillingGCode(halftoneData, options, outputDimensions);
        case 'engraving':
          return this.generateEngravingGCode(halftoneData, options, outputDimensions);
        default:
          throw new GCodeGeneratorError(`Unknown operation type: ${options.operationType}`, 'UNKNOWN_OPERATION');
      }
    } catch (error) {
      throw error instanceof GCodeGeneratorError ? error :
        new GCodeGeneratorError(`G-code generation failed: ${error}`, 'GENERATION_ERROR');
    }
  }

  private static calculateBounds(dots: HalftoneDot[]): {
    minX: number; maxX: number; minY: number; maxY: number;
  } {
    if (dots.length === 0) {
      return { minX: 0, maxX: 0, minY: 0, maxY: 0 };
    }

    let minX = dots[0].x, maxX = dots[0].x;
    let minY = dots[0].y, maxY = dots[0].y;

    dots.forEach(dot => {
      minX = Math.min(minX, dot.x);
      maxX = Math.max(maxX, dot.x);
      minY = Math.min(minY, dot.y);
      maxY = Math.max(maxY, dot.y);
    });

    return { minX, maxX, minY, maxY };
  }

  static estimateJobTime(
    halftoneData: HalftoneData,
    options: GCodeGeneratorOptions,
    outputDimensions: { width: number; height: number }
  ): number {
    try {
      if (!halftoneData.dots.length) return 0;

      const transformedDots = this.transformCoordinates(
        halftoneData.dots,
        halftoneData.width,
        halftoneData.height,
        outputDimensions.width,
        outputDimensions.height
      );

      let totalDistance = 0;
      for (let i = 1; i < transformedDots.length; i++) {
        const prev = transformedDots[i-1];
        const curr = transformedDots[i];
        totalDistance += Math.sqrt(Math.pow(curr.x - prev.x, 2) + Math.pow(curr.y - prev.y, 2));
      }

      if (options.operationType === 'drilling') {
        const rapidTime = totalDistance / (options.feedRate * 2);
        const plungeTime = (transformedDots.length * (options.maxDepth || 1)) / options.plungeRate;
        return rapidTime + plungeTime + 2;
      } else {
        const avgFeedRate = options.feedRate * 0.65;
        return (totalDistance / avgFeedRate) * 60 + 3;
      }
    } catch (error) {
      return 0;
    }
  }

  static validateGCode(gcode: string): { isValid: boolean; errors: string[] } {
    const errors: string[] = [];
    const lines = gcode.split('\n');
    
    let hasStart = false;
    let hasEnd = false;
    
    for (const line of lines) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith(';')) continue;
      
      // Check for basic structure
      if (trimmed.includes('G90') || trimmed.includes('G21') || trimmed.includes('G20')) {
        hasStart = true;
      }
      
      if (trimmed.includes('M30') || trimmed.includes('M2')) {
        hasEnd = true;
      }
      
      // Basic G-code validation
      if (!/^[GM]\d+/.test(trimmed) && !/^[XYZ-\d\.\s]*$/.test(trimmed)) {
        if (!trimmed.match(/^[MSTF]\d+/)) {
          errors.push(`Invalid G-code line: ${trimmed}`);
        }
      }
    }
    
    if (!hasStart) errors.push('Missing initialization commands');
    if (!hasEnd) errors.push('Missing program end command');
    
    return {
      isValid: errors.length === 0,
      errors
    };
  }
}